import { Candidate } from '../types/candidate';

export const initialCandidates: Candidate[] = [
  {
    id: 'cand-1001',
    name: 'Sofía García',
    email: 'sofia.garcia@trackflow.com',
    phone: '+34 612 345 678',
    position: 'Senior Product Designer',
    linkedinUrl: 'https://linkedin.com/in/sofia-garcia',
    cvUrl: 'https://trackflow.com/cv/sofia-garcia.pdf',
    yearsOfExperience: 7,
    status: 'Reviewing',
    stage: 'Screening',
    appliedAt: '2026-09-01',
    notes: [
      { id: 'note-1', content: 'Portfolio muy sólido y alineado con UX de logística.', createdAt: '2026-09-02T10:00:00.000Z' },
      { id: 'note-2', content: 'Necesita revisar disponibilidad para viajar a Zaragoza.', createdAt: '2026-09-03T09:30:00.000Z' },
    ],
  },
  {
    id: 'cand-1002',
    name: 'Mateo López',
    email: 'mateo.lopez@trackflow.com',
    phone: '+1 213 555 0192',
    position: 'Operations Analyst',
    linkedinUrl: 'https://linkedin.com/in/mateo-lopez',
    cvUrl: 'https://trackflow.com/cv/mateo-lopez.pdf',
    yearsOfExperience: 5,
    status: 'Interviewing',
    stage: 'Interview',
    appliedAt: '2026-08-28',
    notes: [
      { id: 'note-3', content: 'Muy buena comprensión de KPI logísticos y reporting.', createdAt: '2026-08-30T12:15:00.000Z' },
    ],
  },
  {
    id: 'cand-1003',
    name: 'Alicia Romero',
    email: 'alicia.romero@trackflow.com',
    phone: '+34 655 882 441',
    position: 'Software Engineer',
    linkedinUrl: 'https://linkedin.com/in/alicia-romero',
    cvUrl: 'https://trackflow.com/cv/alicia-romero.pdf',
    yearsOfExperience: 8,
    status: 'New',
    stage: 'Application',
    appliedAt: '2026-09-05',
    notes: [],
  },
  {
    id: 'cand-1004',
    name: 'Daniel Park',
    email: 'daniel.park@trackflow.com',
    phone: '+1 310 555 0164',
    position: 'Warehouse Systems Manager',
    linkedinUrl: 'https://linkedin.com/in/daniel-park',
    cvUrl: 'https://trackflow.com/cv/daniel-park.pdf',
    yearsOfExperience: 10,
    status: 'Offer',
    stage: 'Offer',
    appliedAt: '2026-08-12',
    notes: [
      { id: 'note-4', content: 'Se ha discutido paquete de compensación y movilidad.', createdAt: '2026-08-27T15:45:00.000Z' },
    ],
  },
];
