'use client';

import Link from 'next/link';
import { useCallback, useEffect, useMemo, useState } from 'react';

type Incident = { id: number; title: string; description: string; category: string; status: 'open' | 'in_progress' | 'resolved' | 'discarded'; origin: 'customer' | 'branch' | 'internal'; branch: string; created_at: string; updated_at: string };
type Summary = { by_status: Record<string, number>; by_category: Record<string, number>; by_origin: Record<string, number>; by_branch: Record<string, number> };
const labels: Record<string, string> = { open: 'Abierta', in_progress: 'En curso', resolved: 'Resuelta', discarded: 'Descartada', customer: 'Cliente', branch: 'Sede', internal: 'Interno', central: 'Central', la_warehouse: 'Los Ángeles — Almacén', la_office: 'Los Ángeles — Oficina', zaragoza_warehouse: 'Zaragoza — Almacén', zaragoza_office: 'Zaragoza — Oficina' };
const categories = ['lost_parcel', 'delivery_failure', 'inventory_discrepancy', 'carrier_issue', 'returns_issue', 'warehouse_incident', 'system_failure', 'client_complaint', 'other'];

export default function IncidentsPage() {
  const [incidents, setIncidents] = useState<Incident[]>([]); const [summary, setSummary] = useState<Summary | null>(null); const [status, setStatus] = useState(''); const [origin, setOrigin] = useState(''); const [branch, setBranch] = useState(''); const [category, setCategory] = useState(''); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [updating, setUpdating] = useState<number | null>(null);
  const query = useMemo(() => new URLSearchParams(Object.entries({ status, origin, branch, category }).filter(([, value]) => value)), [status, origin, branch, category]);
  const load = useCallback(async () => { setLoading(true); setError(''); try { const [listResponse, summaryResponse] = await Promise.all([fetch(`/api/incidents?${query}`), fetch('/api/incidents/summary')]); if (!listResponse.ok || !summaryResponse.ok) throw new Error('No se pudieron cargar las incidencias.'); setIncidents(await listResponse.json()); setSummary(await summaryResponse.json()); } catch (loadError) { setError(loadError instanceof Error ? loadError.message : 'Error de conexión.'); } finally { setLoading(false); } }, [query]);
  useEffect(() => { const timer = window.setTimeout(() => { void load(); }, 0); return () => window.clearTimeout(timer); }, [load]);
  async function changeStatus(incident: Incident, next: Incident['status']) { const previous = incidents; setUpdating(incident.id); setIncidents(previous.map(item => item.id === incident.id ? { ...item, status: next } : item)); try { const response = await fetch(`/api/incidents/${incident.id}/status`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ status: next }) }); if (!response.ok) throw new Error('Transición no permitida.'); setSummary(await (await fetch('/api/incidents/summary')).json()); } catch (statusError) { setIncidents(previous); setError(statusError instanceof Error ? statusError.message : 'No se pudo actualizar el estado.'); } finally { setUpdating(null); } }
  return <main className="incident-page"><header className="incident-header"><div><p className="eyebrow">TrackFlow Ops · Control operativo</p><h1>Incidencias</h1><p>Centraliza y da seguimiento a cada problema operativo.</p></div><div><Link className="back-link" href="/ops">← Volver al panel</Link><Link className="back-link" href="/incidents/new">Registrar incidencia</Link></div></header>{summary && <section className="incident-kpis">{Object.entries(summary.by_status).map(([key, value]) => <div className="metric" key={key}><span>{labels[key] ?? key}</span><strong>{value}</strong></div>)}</section>}<section className="analysis-card"><div className="panel-heading"><h2>Registro de incidencias</h2><div className="incident-filters"><select aria-label="Filtrar estado" value={status} onChange={e => setStatus(e.target.value)}><option value="">Todos los estados</option>{['open', 'in_progress', 'resolved', 'discarded'].map(key => <option key={key} value={key}>{labels[key]}</option>)}</select><select aria-label="Filtrar origen" value={origin} onChange={e => setOrigin(e.target.value)}><option value="">Todos los orígenes</option>{['customer', 'branch', 'internal'].map(key => <option key={key} value={key}>{labels[key]}</option>)}</select><select aria-label="Filtrar categoría" value={category} onChange={e => setCategory(e.target.value)}><option value="">Todas las categorías</option>{categories.map(key => <option key={key}>{key}</option>)}</select><select aria-label="Filtrar sede" value={branch} onChange={e => setBranch(e.target.value)}><option value="">Todas las sedes</option>{['central', 'la_warehouse', 'la_office', 'zaragoza_warehouse', 'zaragoza_office'].map(key => <option key={key}>{key}</option>)}</select></div></div>{error && <div className="incident-error" role="alert">{error} <button onClick={() => void load()}>Reintentar</button></div>}{loading ? <p>Cargando incidencias…</p> : incidents.length === 0 ? <p>No hay incidencias para estos filtros.</p> : <div className="supplier-table-wrap"><table className="supplier-table"><thead><tr><th>ID</th><th>Título</th><th>Categoría</th><th>Origen / sede</th><th>Estado</th><th>Fecha</th></tr></thead><tbody>{incidents.map(incident => <tr key={incident.id}><td>{incident.id}</td><td><strong>{incident.title}</strong><br /><small>{incident.description}</small></td><td>{incident.category}</td><td>{labels[incident.origin]} / {labels[incident.branch]}</td><td><select disabled={updating === incident.id || ['resolved', 'discarded'].includes(incident.status)} value={incident.status} onChange={e => void changeStatus(incident, e.target.value as Incident['status'])}>{['open', 'in_progress', 'resolved', 'discarded'].map(key => <option key={key}>{key}</option>)}</select></td><td>{new Date(incident.created_at).toLocaleDateString()}</td></tr>)}</tbody></table></div>}</section></main>;
}
